- hosts: all
  tasks:
    - name: create service template
      become: yes
      template:
        src: ruby-deplyment.service.j2
        dest: /etc/systemd/system/ruby-deployment.service
        
    - name: copy artifact
      copy:
        src: ruby
        dest: /home/{{ ansible_user }}/ruby
        mode: '0777'

    - name: enable and start service
      become: yes 
      systemd:
        name: ruby-deplyment
        enabled: yes
        state: restarted
        daemon_reload: yes
