- hosts: all
  tasks:
    - name: copy artifact
      copy:
        src: simple-ruby.tar.gz
        dest: /home/{{ ansible_user }}/simple-ruby.tar.gz
        mode: '0777'
    
    - name: extract artifact
      shell: tar -xvf simple-ruby.tar.gz 

    - name: docker build
      shell: docker build -t csagan/simple-ruby
      args:
        chdir: /home/{{ ansible_user }}/simple-ruby

    - name: docker run
      shell: docker run -d --restart always -p 9090:9090 csagan/simple-ruby:latest
      args:
        chdir: /home/{{ ansible_user }}/simple-ruby
